language: php

php:
- 5.4
- 5.5
sudo: false

branches:
  only:
  - master

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - cd $TRAVIS_BUILD_DIR
  - composer install --ignore-platform-reqs --no-interaction
  - printf "\n" | pecl install imagick

script:
  - cd $TRAVIS_BUILD_DIR/test
  - phpunit --configuration phpunit.xml.ci
  - cd $TRAVIS_BUILD_DIR
  - ./vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 -s -p ./src ./test

after_script:
    - php vendor/bin/coveralls
